### ISSUE TITLE
Hi, our internal system has detected issues with php 8.1 

### ISSUE THREAD

**Issue by Faks** [codezero-be/browser-locale#2]
Hi, our internal system has detected issues with php 8.1 with Laravel 9.
`trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home/api_noker_dev/public_html/vendor/codezero/browser-locale/src/BrowserLocale.php on line 112`

**Comment by ivanvermeyen** [comment]
Thanks for reporting!
I think the automated tests didn't fail on this because it's just a warning at this point.
It should be fixed now in 3.2.1 👍
